name: Compilar MistOS S20 FE

on:
  workflow_dispatch:

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps:
    - name: Maximizar Espacio en Disco (Limpieza Extrema)
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 10240
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Configurar Entorno de Compilación
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Configurar Git
      run: |
        git config --global user.name "catpro"
        git config --global user.email "catpro@github.com"

    - name: Inicializar Repositorio de MistOS (Android 16 QPR2)
      run: |
        mkdir -p ~/mistos
        cd ~/mistos
        repo init -u https://github.com/Project-Mist-OS/manifest.git -b sixteen --depth=1

    - name: Sincronizar Código Fuente (Sync)
      run: |
        cd ~/mistos
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Descargar Trees del S20 FE (r8q)
      run: |
        cd ~/mistos
        rm -rf hardware/samsung/
        git clone https://github.com/JoelLucas/android_device_samsung_r8q -b bka-q2 device/samsung/r8q/
        git clone https://github.com/JoelLucas/android_device_samsung_sm8250-common -b bka-q2 device/samsung/sm8250-common/
        git clone https://github.com/JoelLucas/proprietary_vendor_samsung_r8q -b bka-q2 vendor/samsung/r8q/
        git clone https://github.com/JoelLucas/proprietary_vendor_samsung_sm8250-common -b bka-q2 vendor/samsung/sm8250-common/
        git clone https://github.com/JoelLucas/vendor_xiaomi_GoogleCamera -b sixteen vendor/xiaomi/GoogleCamera/
        git clone https://github.com/JoelLucas/android_kernel_samsung_sm8250 -b bka-q2 kernel/samsung/sm8250/
        git clone https://github.com/JoelLucas/android_hardware_samsung -b bka-q2 hardware/samsung/
        git clone https://github.com/JoelLucas/android_hardware_samsung_nfc -b bka-q2 hardware/samsung/nfc/
        git clone https://github.com/JoelLucas/android_hardware_samsung_slsi_nfc -b bka-q2 hardware/samsung_slsi/nfc/

    - name: Compilar la ROM MistOS
      run: |
        cd ~/mistos
        . build/envsetup.sh
        lunch mist_r8q-userdebug
        mka bacon -j$(nproc --all)
